### ISSUE TITLE
Order picker filter options

### ISSUE THREAD

**Issue by snakehead007** [fyrebrick/public#19]
Add a filter button that would filter on:
- ~~Picked items~~
- ~~Used or new items~~
- ~~Remarks (remarks would be different):~~
   - ~~use textbox en wildcards. examples:~~
       - ~~filtering on B* => B120, B1, BOX~~
       - ~~filtering on MX* => MX!, MX101, MX-new~~
       - ~~filtering on 5* => 50, 500, 500B~~
       - ~~filtering on *-new => 504-new, MX-new~~
   - ~~wildcards can be filtered on only having numbers or characters or both.~~

this would be best in a modal.

Needs reviewing that this is a good issue.

**Comment by chiminirc** [comment]
As a seller, I wanted to offer feedback.
My storage system has areas that can be define in remarks as "Tray*" "New01*".  I regularly do this with large lot orders so I know what I need to pick before leaving an area.  My preference is this would function as a "contains" filter by default without the need to enter a wildcard.
It would also be nice to tap a button to hide picked items. "what is left to pick"

**Comment by snakehead007** [comment]
> As a seller, I wanted to offer feedback.
> My storage system has areas that can be define in remarks as "Tray*" "New01*". I regularly do this with large lot orders so I know what I need to pick before leaving an area. My preference is this would function as a "contains" filter by default without the need to enter a wildcard.
> It would also be nice to tap a button to hide picked items. "what is left to pick"

I see, thank you for your feedback ! 
I will create a different issue for the button "what is left to pick". #29

**Comment by snakehead007** [comment]
Tags are added, wildcards were not added to create tags.
