### ISSUE TITLE
On an order that is picked, the back button on the browser displays an order list that hasn't been updated.

### ISSUE THREAD

**Issue by chiminirc** [fyrebrick/public#28]
Windows running Chrome.  If I pick an order and check the PICKED boxes, clicking the back button on the browser takes me back to the list without being updated.  I have to click refresh to see the updated progress bars.

If I click orders then this is fine.  I'm assuming this has more to do with the browser. My concern is that it is high risk to ever have the order list not match the current status of the order.

**Comment by snakehead007** [comment]
This is partly been fixed, the order list updates in realtime. But due to an reverse proxy the wss connection gets blocked. This is to update to orders when going back. 
This issue is already been created #11

**Comment by snakehead007** [comment]
I will close this issue because it has already been created.
This will soon be fixed.
